dist: bionic
language: csharp
mono: none
dotnet: 2.2.105

before_script:
  - export PATH=$PATH:/home/travis/.dotnet/tools

script:
  - dotnet tool install -g dotnet-warp
  - cd ./src/StormworksLuaExtract/
  - dotnet-warp

branches:
  only:
  - master
  - /^v.*$/

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: ./StormworksLuaExtract.exe
  on:
    tags: true