# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  tags:
    include:
    - v*.*.*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Install .NET Core 3.0 (preview)'
    inputs:
      version: '3.0.100-preview6-012264'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: './src/StormworksLuaExtract/StormworksLuaExtract.csproj'
      arguments: '-c Release'
      zipAfterPublish: false
  - task: CopyFiles@2
    displayName: 'Copy build artifacts'
    inputs:
      Contents: '**/publish/StormworksLuaExtract.exe'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: GitHubRelease@0
    displayName: 'GitHub Release'
    inputs:
      gitHubConnection: GitHub-Connection
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'auto'
      assets: '$(Build.ArtifactStagingDirectory)/**/*.exe'
      isDraft: true